adding comment section
jacobgarner/jacob-news-frontend pull request #3
Opened 2023-12-12 16:03 UTC by jacobgarner

2023-12-12 16:35 UTC, popatre requested changes
You have two infinite re-renders. 

Please either make your articles page your home page, or add something to the `/` so we know it not just a blank page

2023-12-12 16:35 UTC, popatre commented on src/components/ArticlesList.jsx
> +  }, [articles]);
this will cause an infinite re-render - put a console log in here to see it

2023-12-12 16:35 UTC, popatre commented on src/components/CommentList.jsx
> +  }, [comments]);
this is an infinite re-render - log it to see

2023-12-13 09:06 UTC, nc-poppy-m approved these changes
Good work! Ready to merge

2023-12-13 09:19 UTC, merged